//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class UtilConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static UtilConfig defaultInstance = ((UtilConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UtilConfig())));
        
        public static UtilConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;port=3306;user=root;password=123456;database=sace;")]
        public string SaceConnection {
            get {
                return ((string)(this["SaceConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;port=3306;user=root;password=123456;database=sace;")]
        public string SaceConnectionBackup {
            get {
                return ((string)(this["SaceConnectionBackup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public decimal ICMS_LOCAL {
            get {
                return ((decimal)(this["ICMS_LOCAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.111111")]
        public decimal ACRESCIMO_PADRAO {
            get {
                return ((decimal)(this["ACRESCIMO_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LOJA_PADRAO {
            get {
                return ((int)(this["LOJA_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Dropbox\\\\SACE\\\\ProdutosAtualizados\\\\")]
        public string PASTA_COMUNICACAO_PRODUTOS_ATUALIZADOS {
            get {
                return ((string)(this["PASTA_COMUNICACAO_PRODUTOS_ATUALIZADOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CLIENTE_PADRAO {
            get {
                return ((int)(this["CLIENTE_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SAIDA_PADRAO {
            get {
                return ((int)(this["SAIDA_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ENTRADA_PADRAO {
            get {
                return ((int)(this["ENTRADA_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public decimal SIMPLES {
            get {
                return ((decimal)(this["SIMPLES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AMBIENTE_NFE {
            get {
                return ((string)(this["AMBIENTE_NFE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("==========================================")]
        public string LINHA_COMPRIMIDA {
            get {
                return ((string)(this["LINHA_COMPRIMIDA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOCUMENTO EMITIDO POR ME OU EPP OPTANTE PELO SIMPLES NACIONAL. NÃO GERA DIREITO A" +
            " CRÉDITO FISCAL DE IPI.")]
        public string NFE_MENSAGEM_PADRAO {
            get {
                return ((string)(this["NFE_MENSAGEM_PADRAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CARTAO_LOJA {
            get {
                return ((int)(this["CARTAO_LOJA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NUMERO_MESES_ANALISAR_ESTOQUE {
            get {
                return ((int)(this["NUMERO_MESES_ANALISAR_ESTOQUE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int NUMERO_DIAS_PRODUTO_STATUS_COMPRADO {
            get {
                return ((int)(this["NUMERO_DIAS_PRODUTO_STATUS_COMPRADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public string C_ORGAO_IBGE_SERGIPE {
            get {
                return ((string)(this["C_ORGAO_IBGE_SERGIPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVIDOR")]
        public string SERVIDOR_NFE {
            get {
                return ((string)(this["SERVIDOR_NFE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SM_VENDAS01")]
        public string SERVIDOR_IMPRIMIR_REDUZIDO1 {
            get {
                return ((string)(this["SERVIDOR_IMPRIMIR_REDUZIDO1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVIDOR")]
        public string SERVIDOR_IMPRIMIR_REDUZIDO2 {
            get {
                return ((string)(this["SERVIDOR_IMPRIMIR_REDUZIDO2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightYellow")]
        public global::System.Drawing.Color BACKCOLOR_FOCUS {
            get {
                return ((global::System.Drawing.Color)(this["BACKCOLOR_FOCUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BACKCOLOR_FOCUS_LEAVE {
            get {
                return ((global::System.Drawing.Color)(this["BACKCOLOR_FOCUS_LEAVE"]));
            }
        }
    }
}
