insert into tb_funcionalidade (codfuncionalidade, descricao)
values
(1, 'Produtos'),
(2, 'Pessoas'),
(3, 'Empresas'),
(4, 'Lojas'),
(5, 'Bancos'),
(6, 'Plano de contas'),
(7, 'Contas Banco/Caixa'),
(8, 'Cartões de credito'),
(9, 'Grupos de produtos'),
(10, 'Grupos de contas'),
(11, 'Usuarios'),
(12, 'Pré-venda'),
(13, 'Pedidos'),
(14, 'Entrada de produtos'),
(15, 'Tranformacoes'),
(16, 'Contas a Pagar'),
(17, 'Contas a receber'),
(18, 'Baixas'),
(19, 'Movimentacao Contas'),
(20, 'Atualização de preços'),
(21, 'Ajuste de Estoque'),
(22, 'Configurações Sistema'),
(23, 'Backup'),
(24, 'Relatorio Cliente'),
(25, 'Relatorio Listagem preços'),
(26, 'Relatorio Estoque'),
(27, 'Relatorio Vendas'),
(28, 'Relatorio Compras');