//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5466
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class SignatureType {
    
    private SignedInfoType signedInfoField;
    
    private SignatureValueType signatureValueField;
    
    private KeyInfoType keyInfoField;
    
    private string idField;
    
    /// <remarks/>
    public SignedInfoType SignedInfo {
        get {
            return this.signedInfoField;
        }
        set {
            this.signedInfoField = value;
        }
    }
    
    /// <remarks/>
    public SignatureValueType SignatureValue {
        get {
            return this.signatureValueField;
        }
        set {
            this.signatureValueField = value;
        }
    }
    
    /// <remarks/>
    public KeyInfoType KeyInfo {
        get {
            return this.keyInfoField;
        }
        set {
            this.keyInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoType {
    
    private SignedInfoTypeCanonicalizationMethod canonicalizationMethodField;
    
    private SignedInfoTypeSignatureMethod signatureMethodField;
    
    private ReferenceType referenceField;
    
    private string idField;
    
    /// <remarks/>
    public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod {
        get {
            return this.canonicalizationMethodField;
        }
        set {
            this.canonicalizationMethodField = value;
        }
    }
    
    /// <remarks/>
    public SignedInfoTypeSignatureMethod SignatureMethod {
        get {
            return this.signatureMethodField;
        }
        set {
            this.signatureMethodField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceType Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoTypeCanonicalizationMethod {
    
    private string algorithmField;
    
    public SignedInfoTypeCanonicalizationMethod() {
        this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class X509DataType {
    
    private byte[] x509CertificateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] X509Certificate {
        get {
            return this.x509CertificateField;
        }
        set {
            this.x509CertificateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyInfoType {
    
    private X509DataType x509DataField;
    
    private string idField;
    
    /// <remarks/>
    public X509DataType X509Data {
        get {
            return this.x509DataField;
        }
        set {
            this.x509DataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureValueType {
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class TransformType {
    
    private string[] xPathField;
    
    private TTransformURI algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XPath")]
    public string[] XPath {
        get {
            return this.xPathField;
        }
        set {
            this.xPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTransformURI Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public enum TTransformURI {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
    httpwwww3org200009xmldsigenvelopedsignature,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
    httpwwww3orgTR2001RECxmlc14n20010315,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceType {
    
    private TransformType[] transformsField;
    
    private ReferenceTypeDigestMethod digestMethodField;
    
    private byte[] digestValueField;
    
    private string idField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceTypeDigestMethod DigestMethod {
        get {
            return this.digestMethodField;
        }
        set {
            this.digestMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DigestValue {
        get {
            return this.digestValueField;
        }
        set {
            this.digestValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceTypeDigestMethod {
    
    private string algorithmField;
    
    public ReferenceTypeDigestMethod() {
        this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoTypeSignatureMethod {
    
    private string algorithmField;
    
    public SignedInfoTypeSignatureMethod() {
        this.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
[System.Xml.Serialization.XmlRootAttribute("retConsCad", Namespace="http://www.portalfiscal.inf.br/nfe", IsNullable=false)]
public partial class TRetConsCad {
    
    private TRetConsCadInfCons infConsField;
    
    private string versaoField;
    
    /// <remarks/>
    public TRetConsCadInfCons infCons {
        get {
            return this.infConsField;
        }
        set {
            this.infConsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TRetConsCadInfCons {
    
    private string verAplicField;
    
    private string cStatField;
    
    private string xMotivoField;
    
    private TUfCons ufField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private System.DateTime dhConsField;
    
    private TCodUfIBGE cUFField;
    
    private TRetConsCadInfConsInfCad[] infCadField;
    
    /// <remarks/>
    public string verAplic {
        get {
            return this.verAplicField;
        }
        set {
            this.verAplicField = value;
        }
    }
    
    /// <remarks/>
    public string cStat {
        get {
            return this.cStatField;
        }
        set {
            this.cStatField = value;
        }
    }
    
    /// <remarks/>
    public string xMotivo {
        get {
            return this.xMotivoField;
        }
        set {
            this.xMotivoField = value;
        }
    }
    
    /// <remarks/>
    public TUfCons UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IE", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dhCons {
        get {
            return this.dhConsField;
        }
        set {
            this.dhConsField = value;
        }
    }
    
    /// <remarks/>
    public TCodUfIBGE cUF {
        get {
            return this.cUFField;
        }
        set {
            this.cUFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infCad")]
    public TRetConsCadInfConsInfCad[] infCad {
        get {
            return this.infCadField;
        }
        set {
            this.infCadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TUfCons {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    TO,
    
    /// <remarks/>
    SU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    CNPJ,
    
    /// <remarks/>
    CPF,
    
    /// <remarks/>
    IE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TCodUfIBGE {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("26")]
    Item26,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("31")]
    Item31,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("32")]
    Item32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("33")]
    Item33,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("35")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("41")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("42")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("43")]
    Item43,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("51")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("53")]
    Item53,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TRetConsCadInfConsInfCad {
    
    private string ieField;
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    private TUf ufField;
    
    private TRetConsCadInfConsInfCadCSit cSitField;
    
    private TRetConsCadInfConsInfCadIndCredNFe indCredNFeField;
    
    private TRetConsCadInfConsInfCadIndCredCTe indCredCTeField;
    
    private string xNomeField;
    
    private string xFantField;
    
    private string xRegApurField;
    
    private string cNAEField;
    
    private System.DateTime dIniAtivField;
    
    private bool dIniAtivFieldSpecified;
    
    private System.DateTime dUltSitField;
    
    private bool dUltSitFieldSpecified;
    
    private System.DateTime dBaixaField;
    
    private bool dBaixaFieldSpecified;
    
    private string iEUnicaField;
    
    private string iEAtualField;
    
    private TEndereco enderField;
    
    /// <remarks/>
    public string IE {
        get {
            return this.ieField;
        }
        set {
            this.ieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public TUf UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    public TRetConsCadInfConsInfCadCSit cSit {
        get {
            return this.cSitField;
        }
        set {
            this.cSitField = value;
        }
    }
    
    /// <remarks/>
    public TRetConsCadInfConsInfCadIndCredNFe indCredNFe {
        get {
            return this.indCredNFeField;
        }
        set {
            this.indCredNFeField = value;
        }
    }
    
    /// <remarks/>
    public TRetConsCadInfConsInfCadIndCredCTe indCredCTe {
        get {
            return this.indCredCTeField;
        }
        set {
            this.indCredCTeField = value;
        }
    }
    
    /// <remarks/>
    public string xNome {
        get {
            return this.xNomeField;
        }
        set {
            this.xNomeField = value;
        }
    }
    
    /// <remarks/>
    public string xFant {
        get {
            return this.xFantField;
        }
        set {
            this.xFantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string xRegApur {
        get {
            return this.xRegApurField;
        }
        set {
            this.xRegApurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string CNAE {
        get {
            return this.cNAEField;
        }
        set {
            this.cNAEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dIniAtiv {
        get {
            return this.dIniAtivField;
        }
        set {
            this.dIniAtivField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dIniAtivSpecified {
        get {
            return this.dIniAtivFieldSpecified;
        }
        set {
            this.dIniAtivFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dUltSit {
        get {
            return this.dUltSitField;
        }
        set {
            this.dUltSitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dUltSitSpecified {
        get {
            return this.dUltSitFieldSpecified;
        }
        set {
            this.dUltSitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dBaixa {
        get {
            return this.dBaixaField;
        }
        set {
            this.dBaixaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dBaixaSpecified {
        get {
            return this.dBaixaFieldSpecified;
        }
        set {
            this.dBaixaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string IEUnica {
        get {
            return this.iEUnicaField;
        }
        set {
            this.iEUnicaField = value;
        }
    }
    
    /// <remarks/>
    public string IEAtual {
        get {
            return this.iEAtualField;
        }
        set {
            this.iEAtualField = value;
        }
    }
    
    /// <remarks/>
    public TEndereco ender {
        get {
            return this.enderField;
        }
        set {
            this.enderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    CNPJ,
    
    /// <remarks/>
    CPF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TUf {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    TO,
    
    /// <remarks/>
    EX,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TRetConsCadInfConsInfCadCSit {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TRetConsCadInfConsInfCadIndCredNFe {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TRetConsCadInfConsInfCadIndCredCTe {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TEndereco {
    
    private string xLgrField;
    
    private string nroField;
    
    private string xCplField;
    
    private string xBairroField;
    
    private string cMunField;
    
    private string xMunField;
    
    private string cEPField;
    
    /// <remarks/>
    public string xLgr {
        get {
            return this.xLgrField;
        }
        set {
            this.xLgrField = value;
        }
    }
    
    /// <remarks/>
    public string nro {
        get {
            return this.nroField;
        }
        set {
            this.nroField = value;
        }
    }
    
    /// <remarks/>
    public string xCpl {
        get {
            return this.xCplField;
        }
        set {
            this.xCplField = value;
        }
    }
    
    /// <remarks/>
    public string xBairro {
        get {
            return this.xBairroField;
        }
        set {
            this.xBairroField = value;
        }
    }
    
    /// <remarks/>
    public string cMun {
        get {
            return this.cMunField;
        }
        set {
            this.cMunField = value;
        }
    }
    
    /// <remarks/>
    public string xMun {
        get {
            return this.xMunField;
        }
        set {
            this.xMunField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string CEP {
        get {
            return this.cEPField;
        }
        set {
            this.cEPField = value;
        }
    }
}
